semicolonDSM/DDYZD_V2_Backend_Node

src/entity/entity-repository/userReposiotry.ts
src/middleware/errorHandler.ts
src/ormconfig.ts
src/service/user.service.ts

fix service logic 
update user repository
fix ormconfig.ts

UPDATE; porvide token service

---

src/middleware/verifyToken.ts
src/router/user.controller.ts
src/service/user.service.ts

fix verify token middleware 
add refresh token service
add show user info service

ADD show user info service

---

src/middleware/verifyToken.ts
src/service/function/userAuthentication.ts
src/service/user.service.ts

fix verify token return logic
fix user info service throw error 
update config value

FIX; user service

---

src/controller/club.controller.ts
src/entity/entity-repository/clubUserViewRepository.ts
src/service/club.service.ts

FIX; club user view repository
UPDATE; club service dependency injection

UPDATE; club service dependency injection

---

src/controller/club.controller.ts
src/router/club.router.ts
src/service/club.service.ts

CREATE; club member service

---

src/controller/club.controller.ts
src/entity/entity-repository/clubRepository.ts
src/router/club.router.ts
src/service/club.service.ts

club repository
service 
controller 
router

CREATE; club recruitment service

---

src/controller/club.controller.ts
src/entity/entity-repository/clubRepository.ts
src/router/club.router.ts
src/service/club.service.ts

find club status repository 
service 
controller 
router

CREATE; club status service 

---

src/controller/club.controller.ts
src/entity/entity-repository/clubRepository.ts
src/router/club.router.ts
src/service/club.service.ts

repository
service 
controller 
router

CREATE; club supplies service 

---

src/controller/club.controller.ts
src/entity/entity-repository/optionRepository.ts
src/entity/entity-repository/supplyRepository.ts
src/router/club.router.ts
src/service/club.service.ts
src/shared/exception.ts

CREATE; supply repository
CREATE; option repository
service 
controller 
router

CREATE; reqeust supply service

---

src/entity/entity-repository/optionRepository.ts

FIX; option repository

---

src/controller/club.controller.ts
src/entity/entity-repository/clubRepository.ts
src/entity/entity-repository/clubUserViewRepository.ts
src/entity/entity-repository/optionRepository.ts
src/entity/entity-repository/supplyRepository.ts
src/middleware/validatoinRequest.ts
src/router/club.router.ts
src/router/user.router.ts
src/service/club.service.ts
src/service/user.service.ts
src/shared/DataTransferObject.ts
src/shared/exception.ts

CREATE; reqeust supply service
CREATE; club supplies service
CREATE; club status service
CREATE; club recruitment service
CREATE; club member service

UPDATE; club service 

---

src/controller/club.controller.ts
src/entity/entity-repository/clubHeadRepository.ts
src/router/club.router.ts
src/service/club.service.ts
src/shared/DataTransferObject.ts

CREATE; club head repository
UPDATE; club info dto 
UPDATE; club info service, controller, router

UPDATE; club info service

---

src/controller/club.controller.ts
src/entity/entity-repository/clubHeadRepository.ts
src/entity/entity-repository/optionRepository.ts
src/entity/entity-repository/supplyRepository.ts
src/router/club.router.ts
src/service/club.service.ts
src/shared/DataTransferObject.ts

service, controller, router
UPDATE; add find one with club with user repository
UPDATE; add modify club supplies schema
UPDATE; add modify club supplies dto

CREATE; modify supply service 

---

src/controller/club.controller.ts
src/entity/entity-repository/supplyRepository.ts
src/router/club.router.ts
src/service/club.service.ts
src/shared/DataTransferObject.ts

CREATE; remove club supplies service

---

src/router/user.router.ts
src/shared/DataTransferObject.ts

define dto 
adapt validation dto

REFACTOR; validation request

---

src/controller/user.controller.ts
src/entity/entity-repository/userReposiotry.ts
src/router/user.router.ts
src/service/user.service.ts

CREATE; add show user gcn

---

src/entity/entity-repository/clubHeadRepository.ts
src/entity/entity-repository/clubUserViewRepository.ts
src/entity/view/ClubUserView.ts
src/service/club.service.ts
src/shared/DataTransferObject.ts

unshift club head
club.service.ts
dto files
ClubUserViewRepository.ts
ClubHeadRepository.ts
ClubUserView.ts

UPDATE; club members service

---

package-lock.json
package.json
src/config/index.ts
src/controller/user.controller.ts
src/entity/entity-repository/userReposiotry.ts
src/router/user.router.ts
src/service/user.service.ts
src/shared/DataTransferObject.ts

user.service.ts
user.controller.ts
user.router.ts
dto file
UserRepository.ts
config/index.ts
add octokit/core package

UPDATE; modify user bio, githubid service

---

src/router/club.router.ts

UPDATE; club.router.ts

---

src/service/club.service.ts
src/shared/DataTransferObject.ts

club의 지원 여부, 지원 종료일자,  동아리 팔로우 여부를 알 수 있도록 수정 
dto file 
club.service.ts

UPDATE; club info service 

---

src/entity/entity-repository/clubRepository.ts

remvoe find info by id method 
update majorname colum to major_name

UPDATE; club repository

---

src/entity/entity-repository/clubRepository.ts
src/service/club.service.ts
src/shared/DataTransferObject.ts

update club recuritment info res obj 
club recuritment info service 
club recuritment info repository

UPDATE; club recuritment info

---

src/router/user.router.ts

UPDATE; user.router.ts

---

src/service/club.service.ts

Club follow API
